{
    "name": "BHZ DRE e CMV",
    "version": "19.0.1.0.0",
    "summary": "Demonstração de Resultados e Custo da Mercadoria Vendida",
    "category": "Accounting",
    "author": "BHZ Sistemas",
    "website": "",
    "depends": ["account"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/bhz_dre_menu.xml",
        "views/bhz_dre_template_views.xml",
        "views/bhz_dre_report_views.xml",
        "views/bhz_dre_wizard_views.xml",
        "report/bhz_dre_report_action.xml",
        "report/bhz_dre_report_templates.xml",
    ],
    "installable": True,
    "application": False,
}
