{
    'name': 'BHZ DRE / CMV',
    'version': '17.0.1.0.0',
    'summary': 'Demonstração de Resultado do Exercício (DRE) com cálculo de CMV',
    'category': 'Accounting/Reporting',
    'author': 'BHZ Sistemas',
    'license': 'OPL-1',
    'depends': ['account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/bhz_dre_menu.xml',
        'views/bhz_dre_template_views.xml',
        'views/bhz_dre_wizard_views.xml',
        'views/bhz_dre_report_views.xml',
        'report/bhz_dre_report_templates.xml',
        'report/bhz_dre_report_action.xml',
    ],
    'installable': True,
    'application': False,
}
