{
    "name": "Theme GuiaBH Website",
    "summary": "Tema moderno e manual para o site GuiaBH no Odoo 19.",
    "description": "Tema limpo e não intrusivo com header, footer e home próprios. Só é aplicado quando selecionado manualmente. Inclui app backend GuiaBH para gestão de conteúdo.",
    "version": "19.0.1.0.0",
    "author": "BHZ Sistemas",
    "website": "https://bhzsistemas.com.br",
    "license": "LGPL-3",
    "category": "Theme/Creative",
    "depends": [
        "base",
        "website",
        "web",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/guiabh_category_views.xml",
        "views/guiabh_event_views.xml",
        "views/guiabh_place_views.xml",
        "views/guiabh_movie_views.xml",
        "views/guiabh_match_views.xml",
        "views/guiabh_news_views.xml",
        "views/guiabh_category_templates.xml",
        "views/guiabh_content_templates.xml",
        "views/guiabh_menus.xml",
        "views/theme/templates.xml",
    ],
    "demo": [],
    "assets": {
        "theme_guiabh_website.assets_frontend": [
            "bhz_guiabh_website/static/src/scss/theme.scss",
            "bhz_guiabh_website/static/src/js/theme_home.js",
        ],
    },
    "installable": True,
    "application": True,
    "theme": True,
}
