{
    'name': 'BHZ GuiaBH Website',
    'summary': 'Site de eventos e lugares de BH com experiência moderna e conteúdo demo.',
    'description': 'Portal GuiaBH com eventos, lugares e guias editáveis no Website Builder.',
    'author': 'BHZ Sistemas',
    'website': 'https://bhzsistemas.com.br',
    'license': 'LGPL-3',
    'category': 'Theme',
    'version': '1.0.0',
    'depends': ['website'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/website_routes.xml',
        'views/guiabh_event_views.xml',
        'views/guiabh_place_views.xml',
        'views/guiabh_taxonomy_views.xml',
        'views/guiabh_ad_views.xml',
        'views/guiabh_banner_views.xml',
        'views/website_templates.xml',
        'views/res_config_settings_views.xml',
        'data/theme_data.xml',
        'data/ir_cron.xml',
    ],
    'qweb': [],
    'demo': [
        'data/demo.xml',
    ],
    'application': False,
    'installable': True,
    'assets': {
        'web.assets_frontend': [
            'bhz_guiabh_website/static/src/scss/guiabh.scss',
            'bhz_guiabh_website/static/src/js/guiabh.js',
        ],
        'website.assets_wysiwyg': [
            'bhz_guiabh_website/static/src/js/guiabh.js',
        ],
    },
    'images': ['static/description/icon.png'],
}
