# -*- coding: utf-8 -*-
{
    'name': 'BHZ GuiaBH Website',
    'summary': 'Site de eventos e lugares de BH com experiência moderna e conteúdo demo.',
    'description': 'Portal GuiaBH com eventos, lugares e guias editáveis no Website Builder.',
    'author': 'BHZ Sistemas',
    'website': 'https://bhzsistemas.com.br',
    'license': 'LGPL-3',
    'category': 'Website',
    'version': '1.0.0',
    'depends': ['base', 'web', 'website'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/demo.xml',
        'data/website_menu.xml',
        'views/website_assets.xml',
        'views/website_routes.xml',
        'views/guiabh_taxonomy_views.xml',
        'views/guiabh_event_views.xml',
        'views/guiabh_place_views.xml',
        'views/website_templates.xml',
        'views/website_pages.xml',
        'views/website_snippets.xml',
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'assets': {},
    'images': ['static/description/icon.png'],
}
