{
    "name": "Theme BHZ Marketplace",
    "summary": "Tema isolado para o marketplace BHZ (home, loja, produto, vendedor, dashboard).",
    "version": "19.0.1.0.0",
    "category": "Theme/eCommerce",
    "author": "BHZ Sistemas",
    "license": "LGPL-3",
    "website": "https://bhzsistemas.com.br",
    "depends": [
        "website",
        "website_sale",
        "portal",
        "website_theme_install",
        "web_editor",
        "bhz_marketplace_core",
        "bhz_marketplace_payouts",
        "bhz_marketplace_returns_disputes",
        "bhz_marketplace_rank_ads",
        "bhz_marketplace_shipping",
        "bhz_marketplace_chat",
    ],
    "data": [
        "data/website.xml",
        "data/menus.xml",
        "data/pages.xml",
        "data/snippets.xml",
        "views/layouts.xml",
        "views/header.xml",
        "views/footer.xml",
        "views/home.xml",
        "views/shop.xml",
        "views/product.xml",
        "views/seller.xml",
        "views/dashboard.xml",
        "views/static_pages.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "theme_bhz_marketplace/static/src/css/marketplace.css",
            "theme_bhz_marketplace/static/src/js/marketplace.js",
        ],
        "web._assets_primary_variables": [],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
