{
    "name": "BHZ AI Org (Agents + Autonomy Governance)",
    "version": "19.0.1.0.0",
    "category": "Productivity",
    "summary": "Cadeia de agentes IA com organograma, tools, políticas, fila e auditoria.",
    "author": "BHZ Sistemas",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "web",
        "sale_management",   
        "crm",               
    ],
    "data": [
        "security/security.xml",
        "security/record_rules.xml",
        "security/ir.model.access.csv",
        "data/default_tools.xml",
        "data/cron.xml",
        "views/menu.xml",
        "views/ai_role_views.xml",
        "views/ai_agent_views.xml",
        "views/ai_tool_views.xml",
        "views/ai_policy_views.xml",
        "views/ai_task_views.xml",
        "views/ai_memory_views.xml",
        "views/ai_audit_log_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "application": True,
    "installable": True,
}
