{
    "name": "BHZ WhatsApp Omni (Starter + Business)",
    "summary": "Atendimento WhatsApp: Starter (QR) + Business (Cloud API) com inbox, IA e anti-abuso",
    "version": "19.0.3.0.0",
    "category": "Tools/Communication",
    "author": "BHZ Sistemas",
    "website": "https://bhzsistemas.com.br",
    "license": "LGPL-3",
    "depends": ["base", "mail", "web"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/mail_activity_type.xml",
        "data/ir_cron.xml",      
        "views/wa_account_views.xml",
        "views/wa_session_views.xml",
        "views/wa_message_views.xml",
        "views/wa_template_views.xml",
        "views/res_config_views.xml",
        "views/menu_views.xml",
        ],
    "installable": True,
}
