{
    "name": "BHZ - Guia de Locais (Cidade)",
    "version": "19.0.1.0.0",
    "category": "Website",
    "summary": "Anuncie locais (bares, restaurantes, parques, museus etc.) no site com páginas públicas.",
    "author": "BHZ Sistemas",
    "license": "LGPL-3",
    "depends": ["base", "website", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/place_stage_data.xml",
        "views/place_views.xml",
        "views/menus.xml",
        "views_website/place_templates.xml",
        "views_website/website_menu.xml",
    ],
    "application": True,
    "installable": True,
}
